---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu-jammy
    image: docker.io/library/ubuntu:jammy
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    v: true
