---
- name: Prepare
  hosts: all
  tasks:
    - name: Install assumed os packages
      ansible.builtin.apt:
        package: "{{ packages }}"
        update_cache: "yes"
        cache_valid_time: "{{ 6 * 3600 }}"
      vars:
        packages:
          - tzdata
