---
kind: pipeline
type: docker
name: default

steps:
  - name: provision
    image: python:3.9-alpine
    environment:
      SSH_PRIVATE_KEY:
        from_secret: ssh_private_key
    commands:
      - apk add --update cargo gcc libffi-dev make musl-dev openssl-dev python3-dev
      - pip install --upgrade pipenv
      - pipenv sync
      - touch vars.yml
      - ssh_private_key=$(mktemp)
      - echo "$SSH_PRIVATE_KEY" > "$ssh_private_key"
      - pipenv run ansible-playbook --private-key "$ssh_private_key" provision.yml
