---
- name: Provision
  hosts: all
  become: yes
  roles:
    - role: adborden.node
      admin_email: "{{ secret_admin_email }}"
      nullmailer_admin_email: "{{ admin_email }}"
      nullmailer_remotes: "{{ secret_nullmailer_remotes }}"
