---
- name: Watchdog
  hosts: raspberry_pi
  become: true
  roles:
    - danmilon.watchdog
  handlers:
    - name: Reboot
      ansible.builtin.reboot:

  tasks:
    - name: Enable raspberry pi hardware watchdog
      ansible.builtin.lineinfile:
        path: /boot/config.txt
        line: dtparam=watchdog=on
        create: true
        state: present
      notify: Reboot
