---
- name: assert node_deploy_ssh_keys is defined
  assert:
    that:
      - node_deploy_ssh_keys is defined
    fail_msg: node_deploy_ssh_keys is required but it is not defined

- name: assert monit_admin_email is defined
  assert:
    that:
      - monit_admin_email is defined
    fail_msg: monit_admin_email is required but it is not defined

- name: assert monit_admin_password is defined
  assert:
    that:
      - monit_admin_password is defined
    fail_msg: monit_admin_password is required but it is not defined

- name: assert nullmailer_admin_email is defined
  assert:
    that:
      - nullmailer_admin_email is defined
    fail_msg: nullmailer_admin_email is required but it is not defined

- name: assert nullmailer_remotes is defined
  assert:
    that:
      - nullmailer_remotes is defined
    fail_msg: nullmailer_remotes is required but it is not defined

- name: set timezone
  community.general.timezone:
    name: "{{ node_timezone }}"
  register: timezone

- name: reboot
  reboot:
  when: timezone is changed
  tags:
    - skip_ansible_lint
    - molecule-notest

- name: install os packages
  apt: package={{ packages }} update_cache=yes cache_valid_time={{ 12 * 3600 }}
  vars:
    packages:
      - nullmailer
      - prometheus-node-exporter
      - monit
      - reboot-notifier
      - unattended-upgrades

- name: create deploy user
  ansible.builtin.user:
    name: deploy
    comment: automated deploy user
    groups: []
    home: /var/lib/deploy
    system: yes
    state: present

- name: authorize ssh keys for deploy user
  ansible.posix.authorized_key:
    user: deploy
    exclusive: yes
    key: "{{ node_deploy_ssh_keys }}"
    state: present

- name: authorize sudo access for deploy user
  copy:
    content: |
      deploy ALL=(ALL) NOPASSWD:ALL
    dest: /etc/sudoers.d/90-deploy
    owner: root
    group: root
    mode: "0440"

- name: configure nullmailer remote
  copy:
    content: "{{ nullmailer_remotes }}"
    dest: /etc/nullmailer/remotes
    owner: mail
    group: mail
    mode: "0600"

- name: configure nullmailer admin address
  copy:
    content: "{{ nullmailer_admin_email }}"
    dest: /etc/nullmailer/adminaddr
    owner: mail
    group: mail
    mode: "0644"

- name: enable prometheus node_exporter
  service: name=prometheus-node-exporter state=started enabled=yes
  tags:
    - molecule-notest

- name: configure monit (system)
  blockinfile:
    block: |
      set alert {{ monit_admin_email }}

      set httpd port 2812 and
        use address localhost  # only accept connection from localhost (drop if you use M/Monit)
        allow localhost        # allow localhost to connect to the server and
        allow {{ monit_admin_user }}:{{ monit_admin_password }} # require user/password
        # TODO enable ssl
        #with ssl {            # enable SSL/TLS and set path to server certificate
        #    pemfile: /etc/ssl/certs/monit.pem
        #}

      check system $HOST
        if loadavg (1min) per core > 2 for 5 cycles then alert
        if loadavg (5min) per core > 1.5 for 10 cycles then alert
        if cpu usage > 95% for 10 cycles then alert
        if memory usage > 75% then alert
        if swap usage > 25% then alert
    dest: /etc/monit/monitrc
    owner: root
    group: root
    mode: "0600"

- name: configure common monit configs
  file:
    src: /etc/monit/conf-available/{{ item }}
    dest: /etc/monit/conf-enabled/{{ item }}
    state: link
  with_items:
    - cron
    - openssh-server

- name: configure monit (root)
  copy:
    content: |
      check filesystem root path /
        if space usage > 90% for 5 cycles then alert
    dest: /etc/monit/conf.d/root
    owner: root
    group: root
    mode: "0644"

- name: configure monit (prometheus)
  copy:
    content: |
      check process prometheus-node-exporter
        start program = "/bin/systemctl start prometheus-node-exporter"
        stop program = "/bin/systemctl stop prometheus-node-exporter"
        if failed port 9100 protocol imap for 5 cycles then restart
        if 3 restarts within 5 cycles then timeout
    dest: /etc/monit/conf.d/prometheus-node-exporter
    owner: root
    group: root
    mode: "0644"
