---
- name: install os packages
  apt: package={{ packages }} update_cache=yes cache_valid_time={{ 12 * 3600 }}
  vars:
    packages:
      - nullmailer
      - prometheus-node-exporter
      - reboot-notifier
      - unattended-upgrades

- name: configure nullmailer
  copy:
    content: "{{ nullmailer_remotes }}"
    dest: /etc/nullmailer/remotes
    owner: mail
    group: mail
    mode: "0600"

- name: enable prometheus node_exporter
  service: name=prometheus-node-exporter state=started enabled=yes
