---
name: commit

on:
  push:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v6
      - name: install poetry
        run: pip install --upgrade poetry
      - name: install dependencies
        run: make setup
      - name: lint
        run: make lint
      - name: test
        run: make test
