---
name: commit

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: snyk
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: install pipenv
        run: pip install --upgrade pipenv
      - name: install dependencies
        run: make setup
      - name: lint
        run: make lint
      - name: test
        run: make test
